Allow to pass mode of the consul definition to avoid token leak.
criteo-forks/consul-cookbook pull request #18
Opened 2019-07-04 15:46 UTC by clems4ever

With the current default mode for the definitions, any user on the machine running
the consul client can read the service definition holding the ACL token.
If an attacker get into the server as a non consul user, he could easily steal
tokens of all registered services.

2019-07-04 16:50 UTC, pierresouchay approved these changes
LGTM, can you check tests?

2019-07-04 18:31 UTC, clems4ever commented
Same issue as previous commit on criteo branch: Chef license.
STDOUT: Chef Development Kit cannot execute without accepting the license

2019-07-04 23:36 UTC, pierresouchay commented
@clems4ever rebase on branch Criteo and tests should be fine

2019-07-05 07:49 UTC, clems4ever commented
It's already on top of Criteo branch.

2019-07-05 07:50 UTC, pierresouchay commented
@clems4ever I don't think so: https://github.com/criteo-forks/consul-cookbook/commits/criteo

2019-07-05 07:59 UTC, clems4ever commented
Done

2019-07-05 10:44 UTC, pierresouchay requested changes
Failed test:
```
×  mode should cmp == "0644"
     
     expected: "0644"
          got: "0640"
     
     (compared using `cmp` matcher)
```

2019-07-10 11:12 UTC, pierresouchay commented
@clems4ever Can you just fix the unit test and I'll merge it

2019-07-10 11:56 UTC, clems4ever commented
yep, sorry. I'm on it.

2019-07-10 14:09 UTC, merged