Rewrite resources to remove Poise dependency
criteo-forks/consul-cookbook pull request #19
Opened 2021-10-04 10:01 UTC by josqu4red

2021-10-05 13:27 UTC, jeremy-clerc requested changes

2021-10-05 13:27 UTC, jeremy-clerc commented on metadata.rb
> +depends 'golang', '< 5.0.0'
< constraints should not be added here, if it breaks the tests, add it to Berksfile.
Else this cookbook may be compatible with Chef 14 while we restrict golang for Chef 14.

2021-10-05 13:27 UTC, jeremy-clerc commented on metadata.rb
>  depends 'poise-archive', '~> 1.3'
Not poise-archive too ?

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/execute.rb
> +default_action(:run)
NIT: Remove parentheses here, for property and action to be consistent with other resources

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/watch.rb
> +default_action(:create)
NIT: Here too remove parantheses, or use parenthenses in other files, for consistency

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/config_v0.rb
> +provides :consul_config do |node|
OPT: consul < 1 is 3 years old, IMHO we could drop support.

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/service.rb
> +# @!property config_file
OPT: As you drop upstart / sysvinit service config, add it to commit message.

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/installation.rb
> +#  ark 'consul' do # TODO: replace with archive_file when Chef>15
Cleanup commented code

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/installation.rb
> +#  link "#{node.config_prefix_path}\\consul.exe" do
Cleanup here too

2021-10-05 13:27 UTC, jeremy-clerc commented on resources/installation.rb
> +#  ark 'consul' do # TODO: replace with archive_file when Chef>15
Or is it supposed to be used ?

2021-10-05 13:27 UTC, jeremy-clerc commented on attributes/default.rb
> +default['consul']['service_shell'] = '/bin/false'
Default via poise ?

2021-10-05 13:27 UTC, jeremy-clerc commented on recipes/default.rb
> +  shell node['consul']['service_shell']
Linked to other comment, if default via poise. If not, why force the shell ?

2021-10-06 10:09 UTC, josqu4red commented on attributes/default.rb
> +default['consul']['service_shell'] = '/bin/false'
`nologin` is preferred but it defaults to `false`.
https://github.com/poise/poise-service/blob/master/lib/poise_service/resources/poise_service_user.rb#L86

2021-10-06 13:34 UTC, josqu4red commented on resources/installation.rb
> +#  ark 'consul' do # TODO: replace with archive_file when Chef>15
Done

2021-10-06 13:34 UTC, josqu4red commented on resources/installation.rb
> +#  link "#{node.config_prefix_path}\\consul.exe" do
Done

2021-10-07 08:41 UTC, josqu4red commented on metadata.rb
>  depends 'poise-archive', '~> 1.3'
I hoped that poise-archive did not rely on the problematic lib, but it is :(

2021-10-13 11:40 UTC, josqu4red commented on recipes/default.rb
> +  shell node['consul']['service_shell']
Not sure to understand, but if `service_shell` is nil, shell will be nil anyways, so guard is useless

2021-10-13 15:01 UTC, jeremy-clerc approved these changes

2021-10-18 14:51 UTC, merged